version: '3.8'
name: killbill
services:
  killbill:
    image: killbill/killbill:latest
    container_name: killbill_testing
    ports:
      - "9098:8080"
    environment:
      # - KILLBILL_DAO_URL=jdbc:mysql://db:3306/killbill
      - KILLBILL_DAO_URL=jdbc:mysql://127.0.0.1:3306/killbill
      - KILLBILL_DAO_USER=root
      - KILLBILL_DAO_PASSWORD=killbill
      - KILLBILL_CATALOG_URI=SpyCarAdvanced.xml
      - KB_org_killbill_invoice_readMaxRawUsagePreviousPeriod=0
      - KB_org_killbill_invoice_usage_missing_lenient=true
  plugin:
    # Enable the Stripe plugin
    plugins:
      - name: killbill-stripe-plugin
        version: 0.21.0
        properties:
          # Stripe API Key (either test or live)
          stripe.api.key: "sk_test_51Q7WJ9E9XjrRrU2JN8uEZx856B8M1UZr0LoMhZPIhwLKatn8WwAM89ie1nwoo71PbFlxlLLMQ6XksvUPvCLbBAOK00jz8u5Yrs"
          
          # Optional: Webhook secret (if you're using webhooks)
          stripe.webhook.secret: "whsec_test_webhook_secret"
 
  kaui:
    image: killbill/kaui:latest
    container_name: kaui_testing
    ports:
      - "9099:8080"
    environment:
      - KAUI_CONFIG_DAO_URL=jdbc:mysql://db:3306/kaui
      - KAUI_CONFIG_DAO_USER=root
      - KAUI_CONFIG_DAO_PASSWORD=killbill
      - KAUI_KILLBILL_URL=http://killbill:8080

  db:
    image: killbill/mariadb:0.24
    container_name: db_testing
    ports:
      - "7088:3306"
    volumes:
      - db_testing_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=killbill

volumes:
  db_testing_data:
    driver: local  # Specify the volume driver (local is default)